### ISSUE TITLE
Duplicate code in key.go

### ISSUE THREAD

**Issue by guillaumemichel** [plprobelab/go-kademlia#101]
There is a lot of duplicate code in [key.go](https://github.com/plprobelab/go-kademlia/blob/468dbe193becfcf4f63adc34b963ec42e827d21e/key/key.go). At the first look, having a distinct type for each keysize doesn't seem like a best practice.

What was the reasoning to replace the [generic key implementation](https://github.com/plprobelab/go-kademlia/blob/ad571a949f2d7e685e2379e0b80a6b1b2a5869db/key/key.go) with the current static one? The generic key implementation seems easier to read and more concise. I am certainly missing the benefits that the current approach brings.

**Comment by iand** [comment]
The duplicate code in key.go is only for convenience. go-kademilia doesn't depend on the key size but having those common ones available makes it easier to test. We could move kad8 and kad32 to kadtest and retain kad256 (perhaps other users might want to supply their own kad160)

The primary reasons for adding a generic typesafe key interface:

1. eliminates checks for key length everywhere a key is used, such as in the routing table. Otherwise we have invalid key length errors to check for basic operations
2. the generic types allow the caller to use their own types when working with go-kademlia
3. it allows more efficient representations of keys rather than assuming a heap allocated byte slice, for example you could implement a Key using a struct of 4 uint64s

**Comment by guillaumemichel** [comment]
OK, I am now convinced :+1+
