### ISSUE TITLE
Optimize Routing Table Module

### ISSUE THREAD

**Issue by iand** [plprobelab/go-kademlia#2]
ETA: 2023-08-31

# Description

Currently most of the DHT Routing Table logic is contained in the repository https://github.com/libp2p/go-libp2p-kbucket. However, having this part of the implementation in a repository distinct from https://github.com/libp2p/go-libp2p-kad-dht is impractical, because of dependency reasons. IMO all code directly concerning the DHT implementation should live in a single repository.

The Minimal Working Modular DHT contains a minimal Routing Table example, without all implementation details and features that are currently available in the https://github.com/libp2p/go-libp2p-kbucket repository (e.g diversity filter). The goal of this subproject is to filter the features of https://github.com/libp2p/go-libp2p-kbucket that are actually useful and migrate them to the refactored DHT implementation. In addition, it would be great to have unit tests thoroughly testing the Routing Table implementation, making sure that the behavior is exactly as expected.

# References

- https://github.com/libp2p/go-libp2p-kbucket

Children:

 - [x] https://github.com/plprobelab/go-kademlia/issues/44
 - [x] https://github.com/plprobelab/go-kademlia/issues/45
 - [x] https://github.com/plprobelab/go-kademlia/issues/47

**Comment by guillaumemichel** [comment]
https://github.com/libp2p/go-libp2p-kbucket is not optimized because it is not using a xor trie (e.g https://github.com/libp2p/go-libp2p-xor, https://github.com/guillaumemichel/py-binary-trie). The basic routing table should make use of a XOR trie. 

We may also be willing to create a `ClientRT`, because the optimized routing table is different for clients for they don't have the same constraints as DHT servers.

We may want to port the `FullRT` (https://github.com/libp2p/go-libp2p-kad-dht/tree/master/fullrt) mechanism (it should be superseded by Reprovide Sweep).

Another idea that has been discussed is to implement a `LazyRT` where a node would keep storing peers beyond the bucket limit, but only refresh peers within the bucket size limit. The RT would contain much more peers and doesn't need to refresh the extra peers, however they may become stale.

Each RT implementation may require its own issue (but not all of them are required before production).

**Comment by guillaumemichel** [comment]
Note that there are multiple possible refresh mechanisms routing tables:
* Crawling the entire network (e.g in the `FullRT` [implementation](https://github.com/libp2p/go-libp2p-kad-dht/blob/ee95d1ab03c47aab03218e18d07483f51e7787e4/fullrt/dht.go#L255))
* Periodically refreshing the complete routing table
* Periodically refreshing each peer that is in the routing table individually (to avoid burst)
* ...

**Comment by iand** [comment]
Last item was https://github.com/libp2p/go-libp2p-kad-dht/issues/936
